blank_issues_enabled: false
contact_links:
  - name: PulseStack Discussions
    url: https://github.com/pulsestack/pulsestack/discussions
    about: Please ask and answer questions here. For general discussion, please don't open an issue.
